"use client";

import { ScreeningDisclaimer } from "@/components/brand/logo";
import { Button } from "@/components/ui/button";
import { DataTable, EmptyState, PageHeader, Skeleton } from "@/components/ui/display";
import { RiskBadge, RiskBar } from "@/components/ui/risk";
import { PRODUCT } from "@/lib/constants";
import { formatDate } from "@/lib/format";
import { moduleFullLabel, moduleLabel, OVERALL_CONCERN_NOTE } from "@/lib/risk";
import { downloadText } from "@/lib/utils";
import { usePreferences } from "@/providers/preferences-provider";
import { useData } from "@/providers/data-provider";
import type { AssessmentType, Report, Student } from "@/types";
import { FileText } from "lucide-react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { toast } from "sonner";

export function ReportsView() {
  const { reports, students, createReport, ready } = useData();
  const { preferences } = usePreferences();
  const router = useRouter();
  const rows = [...reports].sort((a, b) => b.createdAt.localeCompare(a.createdAt));

  if (!ready) {
    return (
      <div>
        <PageHeader title="Reports" subtitle="Generate and manage student screening summaries." />
        <Skeleton className="h-80" />
      </div>
    );
  }

  return (
    <div>
      <PageHeader title="Reports" subtitle="Generate and manage student screening summaries." />
      {rows.length === 0 ? (
        <EmptyState icon={<FileText className="h-5 w-5" />} title="No reports yet." description="Open a student profile and generate a screening summary." action={<Link href="/students"><Button>View students</Button></Link>} />
      ) : (
        <DataTable
          caption="Reports"
          rows={rows}
          rowKey={(row) => row.id}
          columns={[
            { key: "student", header: "Student", cell: (row: Report) => students.find((student) => student.id === row.studentId)?.name ?? "Student" },
            { key: "date", header: "Report Date", cell: (row) => formatDate(row.createdAt, preferences.dateFormat) },
            { key: "included", header: "Included Assessments", cell: (row) => row.included.map((item) => moduleLabel[item]).join(", ") || "None yet" },
            { key: "by", header: "Generated By", cell: (row) => row.generatedBy },
            { key: "status", header: "Status", cell: (row) => <span className="rounded-full bg-risk-low-bg px-2 py-1 text-xs text-risk-low">{row.status === "ready" ? "Ready" : "Draft"}</span> },
            {
              key: "action",
              header: "Action",
              cell: (row) => (
                <div className="flex gap-2">
                  <Link href={`/reports/${row.studentId}`}><Button size="sm" variant="secondary">Preview</Button></Link>
                  <Button size="sm" variant="tertiary" onClick={() => router.push(`/reports/${row.studentId}?download=1`)}>Download Report</Button>
                  <Button size="sm" variant="tertiary" onClick={async () => { await createReport(row.studentId); toast.success("Report regenerated"); }}>Regenerate</Button>
                </div>
              ),
            },
          ]}
        />
      )}
    </div>
  );
}

export function ReportPreview({ studentId }: { studentId: string }) {
  const { students, assessments, observations, createReport } = useData();
  const { preferences } = usePreferences();
  const router = useRouter();
  const student = students.find((item) => item.id === studentId);
  if (!student) {
    return <EmptyState icon={<FileText className="h-5 w-5" />} title="Report unavailable." description="This student is not in the current records." />;
  }
  const latest = (type: AssessmentType) =>
    assessments.filter((item) => item.studentId === student.id && item.type === type).sort((a, b) => b.createdAt.localeCompare(a.createdAt))[0];
  const modules: AssessmentType[] = ["dyslexia", "dysgraphia", "adhd"];
  const timeline = assessments.filter((item) => item.studentId === student.id).sort((a, b) => a.createdAt.localeCompare(b.createdAt));

  const download = () => {
    const html = `<!doctype html><html><head><meta charset="utf-8"><title>LearnGuard Screening Report ${student.code}</title></head><body><h1>LearnGuard Screening Report</h1><p>${student.name} · ${student.code}</p><p>${PRODUCT.reportDisclaimer}</p></body></html>`;
    downloadText(`LearnGuard-Screening-Report-${student.code}.html`, html, "text/html");
    toast.success("Report downloaded");
  };

  return (
    <div>
      <PageHeader
        title="Report Preview"
        subtitle="Review the screening summary before printing or downloading."
        actions={
          <div className="no-print flex gap-2">
            <Button onClick={download}>Download Report</Button>
            <Button variant="secondary" onClick={() => window.print()}>Print</Button>
            <Button variant="secondary" onClick={async () => { await createReport(student.id); toast.success("Report regenerated"); }}>Regenerate</Button>
            <Button variant="tertiary" onClick={() => router.push("/reports")}>Close</Button>
          </div>
        }
      />
      <article id="report-preview" className="mx-auto max-w-3xl rounded-2xl border border-line bg-surface p-8">
        <p className="text-xs font-semibold tracking-[0.08em] text-primary-dark">LEARNGUARD</p>
        <h2 className="mt-2 text-2xl font-bold text-heading">Screening Report</h2>
        <p className="mt-1 text-sm text-muted">{formatDate(new Date().toISOString(), preferences.dateFormat)}</p>
        <section className="mt-8">
          <h3 className="text-base font-semibold text-heading">Student Information</h3>
          <dl className="mt-3 grid gap-2 text-sm sm:grid-cols-2">
            <div><dt className="text-muted">Name</dt><dd>{student.name}</dd></div>
            <div><dt className="text-muted">ID</dt><dd>{student.code}</dd></div>
            <div><dt className="text-muted">Grade / age</dt><dd>Grade {student.grade} · Age {student.age}</dd></div>
            <div><dt className="text-muted">School</dt><dd>{student.school} · {student.section}</dd></div>
            <div><dt className="text-muted">Consent</dt><dd>{student.consentVerified ? `Verified ${student.consentDate ?? ""}` : "Pending"}</dd></div>
          </dl>
        </section>
        <section className="mt-8">
          <h3 className="text-base font-semibold text-heading">Assessment Summary</h3>
          <div className="mt-3 space-y-3">
            {modules.map((type) => {
              const result = student.riskProfile[type];
              return (
                <div key={type}>
                  <div className="mb-1 flex items-center justify-between text-sm">
                    <span>{moduleLabel[type]}</span>
                    {result ? <RiskBadge level={result.level} /> : <span className="text-muted">Not assessed</span>}
                  </div>
                  {result ? <RiskBar value={result.score} level={result.level} /> : null}
                </div>
              );
            })}
          </div>
          <p className="mt-4 text-sm leading-6 text-body">{student.riskProfile.overallNote}</p>
          <p className="mt-2 text-xs leading-5 text-faint">{OVERALL_CONCERN_NOTE}</p>
        </section>
        {modules.map((type) => {
          const item = latest(type);
          if (!item) return null;
          return (
            <section key={type} className="mt-8">
              <h3 className="text-base font-semibold text-heading">{moduleFullLabel[type]}</h3>
              <p className="mt-2 text-sm text-muted">{item.score}% · {formatDate(item.createdAt, preferences.dateFormat)}</p>
              <p className="mt-2 text-sm leading-6 text-body">{item.explanation}</p>
              <ul className="mt-2 text-sm text-muted">
                {item.factors.map((factor) => <li key={factor.label}>{factor.label}: {factor.detail ?? factor.impact}</li>)}
              </ul>
            </section>
          );
        })}
        <section className="mt-8">
          <h3 className="text-base font-semibold text-heading">Risk Timeline</h3>
          <ul className="mt-2 space-y-1 text-sm text-body">
            {timeline.map((item) => (
              <li key={item.id}>{formatDate(item.createdAt, preferences.dateFormat)} · {moduleLabel[item.type]} · {item.score}%</li>
            ))}
          </ul>
        </section>
        <section className="mt-8">
          <h3 className="text-base font-semibold text-heading">Recommended Next Steps</h3>
          <div className="mt-3 space-y-3">
            {modules.map((type) => {
              const item = latest(type);
              return (
                <div key={type}>
                  <p className="text-sm font-medium text-heading">{moduleLabel[type]}</p>
                  <p className="mt-1 text-sm leading-6 text-body">{item?.recommendation ?? "Not assessed yet."}</p>
                </div>
              );
            })}
          </div>
          {student.riskProfile.overallNote ? (
            <p className="mt-4 text-sm leading-6 text-body"><span className="font-medium text-heading">Overall teacher guidance. </span>{student.riskProfile.overallNote}</p>
          ) : null}
        </section>
        {observations.filter((item) => item.studentId === student.id).length ? (
          <section className="mt-8">
            <h3 className="text-base font-semibold text-heading">Recent observations</h3>
            <ul className="mt-2 text-sm text-body">
              {observations.filter((item) => item.studentId === student.id).slice(0, 3).map((item) => (
                <li key={item.id}>{item.date} · {item.subject} · {item.durationMin} min</li>
              ))}
            </ul>
          </section>
        ) : null}
        <p className="mt-8 text-sm leading-6 text-heading">{PRODUCT.reportDisclaimer}</p>
        <ScreeningDisclaimer className="mt-3" />
      </article>
    </div>
  );
}

export type { Student };
